In [5]:
import numpy as np
l1=[1,2,3,4]
np.array(l1)


array([1, 2, 3, 4])

In [14]:
import numpy as np
n2=np.array([[1,2,3,4,],[5,6,7,8]])

In [15]:
n2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
type(n2)

numpy.ndarray

In [18]:
n3=np.zeros((5,5))
n3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# if want some specific number in our m-dimensional array so we use full 

In [26]:
import numpy as np
n1=np.full((2,3),10)

In [27]:
n1

array([[10, 10, 10],
       [10, 10, 10]])

In [28]:
n2=np.arange(50,101) # for range we use range function

n2

In [29]:
n2

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [32]:
n1=np.arange(10,101,10)


In [35]:
n1

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
#for random number we use random function with randint

In [56]:
import numpy as np
n1=np.random.randint(1,10,10)

n1

In [57]:
n1

array([4, 7, 1, 8, 5, 7, 7, 9, 3, 9])

In [ ]:
# for knowing the shape of multidimensional array .we use  shape function

In [61]:
import numpy as np
n1=np.array([[1,2,3],[5,6,7]])

In [62]:
n1.shape

(2, 3)

In [68]:
n1.shape=(3,2) # for changing the dimension of array
n1

array([[1, 2],
       [3, 5],
       [6, 7]])

In [ ]:
# for joining two array into one one array

In [70]:
import numpy as np
n1=np.array([1,2,3])
n2=np.array([5,6,7])   
n3=np.vstack((n1,n2))    # vstack is use for vertical joinging 

In [71]:
n3

array([[1, 2, 3],
       [5, 6, 7]])

In [72]:
np.hstack((n1,n2))    # hstack is use for horizontal joining 

array([1, 2, 3, 5, 6, 7])

In [77]:
np.column_stack((n1,n2))

array([[1, 5],
       [2, 6],
       [3, 7]])

In [2]:
import numpy as np
n1=np.array([30,50,70,60])
n2=np.array([40,50,60,80])

In [3]:
np.intersect1d(n1,n2)  # intersect1d is use for finding common element in both array

array([50, 60])

In [4]:
np.setdiff1d(n1,n2)    # setdiff1d is use for finding unique in both array

array([30, 70])

In [5]:
np.setdiff1d(n2,n1)

array([40, 80])

In [ ]:
# simple mathematics like add,sub,mul and div

In [6]:
import numpy as np
n1=np.array([10,20])
n2=np.array([30,40])
np.sum([n1,n2])

100

In [ ]:
#if to do addition in vertical then we use axix=0


In [8]:
np.sum([n1,n2] ,axis=0)

array([40, 60])

In [9]:
np.sum([n1,n2] ,axis=1) # for horizontal we use axis=1

array([30, 70])

In [ ]:
#for scalar mathematics 

In [10]:
import numpy as np
n1=np.array([10,20,30])
n1=n1+1
n1

array([11, 21, 31])

In [11]:
n1=n1*2
n1

array([22, 42, 62])

In [12]:
n1=n1/2
n1

array([11., 21., 31.])

In [ ]:
#for finding mean ,median and standard deviation

In [ ]:
import numpy as np
n1=np.array([10,20,30,40,50])


In [13]:
np.mean(n1)  # mean function is use for finding mean

21.0

In [14]:
np.std(n1) # for finding stadard deviation we use std

8.16496580927726

In [15]:
np.median(n1)  # for finding median we use medjian3

21.0

In [ ]:
# for save and load a array we use save and load

In [16]:
import numpy as np
n1=np.array([10,20,30,40,50])
np.save('my_numpy',n1)

In [17]:
n2=np.load('my_numpy.npy')
n2

array([10, 20, 30, 40, 50])